# docker-compose.yml
version: '3.8'
services:
  chroma:
    image: chromadb/chroma
    container_name: chroma_db
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - ALLOW_RESET=true
    restart: unless-stopped

volumes:
  chroma_data:
    name: chroma_data